### ISSUE TITLE
How to build apps for older Nano S e.g. 1.4.2?

### ISSUE THREAD

**Issue by loupiote** [LedgerHQ/ledger-app-builder#64]
The NANOS_SDK in the Docker image (ledger-app-builder:latest) seems to be configured only for TARGET_ID=0x31100004 i.e.  Nano S >= 1.5.x. 

Is there a way to build apps that can run on older Nano S, e.g. 1.4.2 (TARGET_ID 0x31100003) ?

This would be for recovery situations where only an old nano S is available and seed is lost, so firmware update could be risky.

Would this be possible with the "Legacy" docker image? If yes, does that "Legacy" docker image need to be modified to build apps for those old Nano S?

Note: I tried building with docker image ledger-app-builder:latest , changing TARGET_ID to 0x31100003 in /opt/nanos-secure-sdk/include/bolos_target.h, but the app crashes when started on the Nano S 1.4.2.

**Comment by xchapron-ledger** [comment]
Hello @loupiote 
For each device OS version, there is a corresponding SDK version, that the reason why your app is crashing when launched.
The ledger-app builder docker image is set up to build application on the last OS available for each Ledger devices. So currently for NanoS it's for OS 2.1.0.

In order to build an app for NanoS OS 1.4.2, you should use the corresponding SDK, and therefore the tag `nanos-1421` or `nanos-1422` on https://github.com/LedgerHQ/nanos-secure-sdk/tags.

As far as I know, this is a very old version and the docker image wasn't available at that time. So you should either create one, by tracking the SDK version you want in here: https://github.com/LedgerHQ/ledger-app-builder/blob/master/lite/Dockerfile#L54 and hopefully the dependency didn't change much.

**Comment by loupiote** [comment]
Ok, thanks.

> For each device OS version, there is a corresponding SDK version, that the reason why your app is crashing when launched.

That's not completely true, because the current Nano S SDK appears to work on several version of the Nano S firmware :) - But i get your point.

**Comment by xchapron-ledger** [comment]
> Ok, thanks.
> 
> > For each device OS version, there is a corresponding SDK version, that the reason why your app is crashing when launched.
> 
> That's not completely true, because when i build my app with the current Nano S SDK appears to work on several version of the Nano S firmware :) - But i get your point.

It might partially work, that depend on the changes that occurs from an OS version to another.
If there is a change in a syscall for example, it introduce an incompatibility. Now if you don't use that specific syscall, you will not see it.
